---
language: python
services: docker

matrix:
  include:
    - os: linux
      dist: xenial

before_script:
  - cd ../
  - mv ansible-role-install-windows-rdgateway-certificate install-windows-rdgateway-certificate
  - cd install-windows-rdgateway-certificate

install:
  - pip install molecule docker

script:
  - molecule lint
