---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: molecule-centos6
    image: centos:6
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=60s
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
